version: '3.8'

services:
  postgres:
    build: ./postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: class_schedule
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  tomcat:
    build: ./build/libs/
    container_name: tomcat-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend-app
    working_dir: /app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - tomcat
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
